version: '3.9'

services:
  db:
    container_name: postgres_db
    image: postgres:15
    env_file: .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
    expose:
      - '5432'
    networks:
      - bridge_net

  infill:
    container_name: infill
    build: ./infill/
    env_file: .env
    command:
      - ${NUM_RECORDS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      infill:
        condition: service_completed_successfully
    ports:
      - '8080:80'
    networks:
      - bridge_net

volumes:
  db_data:

networks:
  bridge_net:
    driver: bridge