version: '3.9'

services:
  db:
    container_name: postgres_db
    image: postgres:15
    env_file: .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    expose:
      - '5432'

volumes:
  db_data: